<?php

return [
    'nom' => 'Histoire',
    'slug' => 'histoire',
    'description' => 'Des pyramides à la Lune, les moments qui ont changé le monde.',
    'onglet' => 'corail',
    'quiz' => [
        [
            'titre' => 'Grandes dates',
            'slug' => 'grandes-dates',
            'description' => 'Ces années que tout le monde a déjà entendues.',
            'questions' => [
                ['En quelle année l\'homme a-t-il marché sur la Lune pour la première fois ?', ['1969', '1959', '1975', '1981'],
                    'En juillet 1969, Neil Armstrong pose le pied sur la Lune lors de la mission Apollo 11.', 'À la fin des années 1960.'],
                ['En quelle année la Révolution française a-t-elle commencé ?', ['1789', '1815', '1715', '1848'],
                    'La Révolution française commence en 1789. La prise de la Bastille, le 14 juillet, en est le symbole.', 'L\'année de la prise de la Bastille.'],
                ['Quel mur est tombé en 1989 ?', ['Le mur de Berlin', 'La Grande Muraille', 'Le mur d\'Hadrien', 'Le mur des Lamentations'],
                    'Le mur de Berlin séparait la ville en deux depuis 1961. Sa chute, en novembre 1989, annonce la réunification de l\'Allemagne.', 'Il coupait une ville allemande en deux.'],
                ['En quelle année la Seconde Guerre mondiale s\'est-elle terminée ?', ['1945', '1918', '1939', '1950'],
                    'La Seconde Guerre mondiale se termine en 1945. Elle avait commencé en 1939. 1918 marque la fin de la Première.', 'Elle avait commencé en 1939.'],
                ['Qui a été le premier président des États-Unis ?', ['George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams'],
                    'George Washington devient le premier président des États-Unis en 1789. La capitale porte son nom.', 'La capitale porte son nom.'],
                ['Quel navigateur atteint l\'Amérique en 1492 ?', ['Christophe Colomb', 'Vasco de Gama', 'Fernand de Magellan', 'Marco Polo'],
                    'Christophe Colomb pensait rejoindre l\'Asie par l\'ouest. Il atteint les Antilles en 1492.', 'Il pensait arriver en Inde.'],
                ['En quelle année Napoléon est-il battu à Waterloo ?', ['1815', '1812', '1805', '1821'],
                    'Waterloo, en Belgique actuelle, est la dernière bataille de Napoléon, en juin 1815. 1805 est l\'année d\'Austerlitz et 1812, celle de la retraite de Russie.', 'Trois ans après la retraite de Russie.'],
                ['Quelle invention de Gutenberg, vers 1450, a changé la diffusion des livres ?', ['L\'imprimerie à caractères mobiles', 'La machine à vapeur', 'Le télégraphe', 'Le papier'],
                    'Gutenberg met au point l\'imprimerie à caractères mobiles : les livres ne sont plus recopiés à la main. Le papier, lui, avait été inventé bien avant, en Chine.', 'Il permet de reproduire un texte sans le recopier.'],
            ],
        ],
        [
            'titre' => 'Civilisations anciennes',
            'slug' => 'civilisations-anciennes',
            'description' => 'Égypte, Rome, Mali, Dahomey : des empires et leurs traces.',
            'questions' => [
                ['Quel peuple a construit les pyramides de Gizeh ?', ['Les Égyptiens', 'Les Romains', 'Les Grecs', 'Les Mayas'],
                    'Les pyramides de Gizeh ont été bâties par les anciens Égyptiens, il y a environ 4 500 ans, comme tombeaux de pharaons.', 'Des tombeaux de pharaons.'],
                ['Quelle langue les Romains parlaient-ils et écrivaient-ils ?', ['Le latin', 'Le grec', 'L\'hébreu', 'Le sanskrit'],
                    'Les Romains parlaient le latin, d\'où viennent le français, l\'italien, l\'espagnol, le portugais et le roumain.', 'Le français en descend.'],
                ['Quel empereur du Mali est célèbre pour son pèlerinage à La Mecque en 1324 ?', ['Mansa Moussa', 'Soundiata Keïta', 'Askia Mohammed', 'Béhanzin'],
                    'Mansa Moussa traverse le désert avec une caravane chargée d\'or. Soundiata Keïta a fondé l\'empire du Mali, Askia Mohammed a régné sur l\'empire songhaï et Béhanzin sur le Dahomey.', 'Son nom commence par un titre royal : « Mansa ».'],
                ['Dans quelle cité grecque la démocratie est-elle née, dans l\'Antiquité ?', ['Athènes', 'Sparte', 'Rome', 'Troie'],
                    'La démocratie naît à Athènes : les citoyens y votent les lois eux-mêmes. Sparte, sa rivale, était gouvernée par des rois et des anciens.', 'Aujourd\'hui capitale de la Grèce.'],
                ['Quel royaume avait pour capitale Abomey ?', ['Le royaume du Dahomey', 'L\'empire du Ghana', 'Le royaume ashanti', 'L\'empire songhaï'],
                    'Abomey, dans l\'actuel Bénin, était la capitale du royaume du Dahomey. Ses palais royaux sont inscrits au patrimoine mondial de l\'Unesco.', 'Il se trouvait dans l\'actuel Bénin.'],
                ['Comment appelle-t-on l\'écriture des anciens Égyptiens ?', ['Les hiéroglyphes', 'Le cunéiforme', 'L\'alphabet latin', 'Les runes'],
                    'Les Égyptiens écrivaient en hiéroglyphes, de petits dessins. Le cunéiforme vient de Mésopotamie et les runes, du nord de l\'Europe.', 'De petits dessins.'],
                ['Qui était Jules César ?', ['Un général et homme politique romain', 'Un pharaon', 'Un philosophe grec', 'Un empereur chinois'],
                    'Jules César, général romain, conquiert la Gaule puis prend le pouvoir à Rome. Il est assassiné en 44 avant J.-C.', 'Il a conquis la Gaule.'],
                ['Quel peuple d\'Amérique centrale a créé un calendrier très précis et une écriture en glyphes ?', ['Les Mayas', 'Les Vikings', 'Les Celtes', 'Les Mongols'],
                    'Les Mayas, au Mexique et au Guatemala actuels, étaient d\'excellents astronomes et ont laissé de nombreuses inscriptions.', 'Ils vivaient au Mexique et au Guatemala actuels.'],
            ],
        ],
    ],
];
