<?php

return [
    'nom' => 'Géographie',
    'slug' => 'geographie',
    'description' => 'Océans, capitales et fleuves, du bout de la rue au bout du monde.',
    'onglet' => 'menthe',
    'quiz' => [
        [
            'titre' => 'Le tour du monde',
            'slug' => 'le-tour-du-monde',
            'description' => 'Les records et les capitales de la planète.',
            'questions' => [
                ['Quel est le plus grand océan du monde ?', ['Le Pacifique', 'L\'Atlantique', 'L\'océan Indien', 'L\'Arctique'],
                    'Le Pacifique couvre à lui seul près d\'un tiers de la surface de la Terre.', 'Son nom veut dire « paisible ».'],
                ['Quel est le plus long fleuve d\'Afrique ?', ['Le Nil', 'Le Congo', 'Le Niger', 'Le Zambèze'],
                    'Le Nil parcourt plus de 6 000 km avant de se jeter dans la Méditerranée, en Égypte.', 'Il traverse l\'Égypte.'],
                ['Quelle est la capitale du Canada ?', ['Ottawa', 'Toronto', 'Montréal', 'Vancouver'],
                    'La capitale du Canada est Ottawa. Toronto est la plus grande ville du pays.', 'Ce n\'est pas la plus grande ville.'],
                ['Quel est le plus haut sommet du monde ?', ['L\'Everest', 'Le Kilimandjaro', 'Le mont Blanc', 'L\'Aconcagua'],
                    'L\'Everest, dans l\'Himalaya, culmine à près de 8 850 m. Le Kilimandjaro est le plus haut sommet d\'Afrique.', 'Il est dans l\'Himalaya.'],
                ['Sur quel continent se trouve le Sahara ?', ['L\'Afrique', 'L\'Asie', 'L\'Océanie', 'L\'Amérique du Sud'],
                    'Le Sahara, le plus grand désert chaud du monde, couvre le nord de l\'Afrique.', 'Au nord d\'un grand continent.'],
                ['Quel pays compte le plus d\'habitants ?', ['L\'Inde', 'La Chine', 'Les États-Unis', 'L\'Indonésie'],
                    'Selon l\'ONU, l\'Inde est devenue en 2023 le pays le plus peuplé du monde, devant la Chine.', 'Elle a dépassé la Chine récemment.'],
                ['Quelle est la capitale de l\'Australie ?', ['Canberra', 'Sydney', 'Melbourne', 'Perth'],
                    'Canberra a été construite pour être la capitale, à mi-chemin entre Sydney et Melbourne, les deux grandes villes rivales.', 'Une ville construite exprès.'],
                ['Quel pays a la forme d\'une botte ?', ['L\'Italie', 'La Grèce', 'Le Portugal', 'La Croatie'],
                    'L\'Italie s\'avance dans la Méditerranée en forme de botte. La Sicile est le ballon au bout du pied.', 'Sa capitale est Rome.'],
            ],
        ],
        [
            'titre' => 'L\'Afrique de l\'Ouest',
            'slug' => 'l-afrique-de-l-ouest',
            'description' => 'Capitales, fleuves et monnaies de la région.',
            'questions' => [
                ['Quelle est la capitale officielle du Bénin ?', ['Porto-Novo', 'Cotonou', 'Parakou', 'Abomey'],
                    'Porto-Novo est la capitale officielle du Bénin. Cotonou, la plus grande ville, accueille le siège du gouvernement.', 'Ce n\'est pas la plus grande ville.'],
                ['Quel fleuve traverse Bamako et Niamey ?', ['Le Niger', 'Le Sénégal', 'La Volta', 'Le Congo'],
                    'Le Niger traverse le Mali, le Niger et le Nigeria avant de rejoindre l\'océan. Il a donné son nom à deux pays.', 'Il a donné son nom à deux pays.'],
                ['Quelle est la capitale du Ghana ?', ['Accra', 'Kumasi', 'Lomé', 'Abidjan'],
                    'Accra est la capitale du Ghana. Kumasi était la capitale du royaume ashanti. Lomé est au Togo, Abidjan en Côte d\'Ivoire.', 'Une ville sur la côte.'],
                ['Quel est le pays le plus peuplé d\'Afrique ?', ['Le Nigeria', 'L\'Égypte', 'L\'Éthiopie', 'La RD Congo'],
                    'Le Nigeria compte plus de 200 millions d\'habitants, la plus grande population du continent.', 'Le voisin oriental du Bénin.'],
                ['Quelle est la capitale du Sénégal ?', ['Dakar', 'Saint-Louis', 'Thiès', 'Bamako'],
                    'Dakar est la capitale du Sénégal. Saint-Louis l\'a été avant elle, à l\'époque coloniale.', 'Elle est tout à l\'ouest du continent.'],
                ['Quel lac, partagé par quatre pays, a beaucoup rétréci depuis les années 1960 ?', ['Le lac Tchad', 'Le lac Victoria', 'Le lac Volta', 'Le lac Kivu'],
                    'Le lac Tchad est partagé entre le Tchad, le Cameroun, le Niger et le Nigeria. Sécheresses et irrigation l\'ont fortement réduit.', 'Il a donné son nom à un pays.'],
                ['Quelle monnaie utilise-t-on au Bénin, au Sénégal et en Côte d\'Ivoire ?', ['Le franc CFA', 'Le naira', 'Le cedi', 'Le dalasi'],
                    'Ces pays utilisent le franc CFA d\'Afrique de l\'Ouest. Le naira est la monnaie du Nigeria, le cedi celle du Ghana, le dalasi celle de la Gambie.', 'Une monnaie commune à plusieurs pays.'],
                ['Quelle ville est la capitale économique de la Côte d\'Ivoire ?', ['Abidjan', 'Yamoussoukro', 'Bouaké', 'San-Pédro'],
                    'Abidjan est la capitale économique. Yamoussoukro est la capitale politique depuis 1983.', 'Ce n\'est pas la capitale politique.'],
            ],
        ],
    ],
];
