<?php

return [
    'nom' => 'Langue française',
    'slug' => 'langue-francaise',
    'description' => 'Orthographe, grammaire et expressions : les pièges du français.',
    'onglet' => 'citron',
    'quiz' => [
        [
            'titre' => 'Orthographe et grammaire',
            'slug' => 'orthographe-et-grammaire',
            'description' => 'Les accords et les pluriels qui font douter.',
            'questions' => [
                ['Quel est le pluriel de « cheval » ?', ['Des chevaux', 'Des chevals', 'Des chevauxs', 'Des chevales'],
                    'La plupart des noms en -al font leur pluriel en -aux : un cheval, des chevaux. Quelques exceptions : des bals, des festivals, des carnavals.', 'Comme « journal ».'],
                ['Complète : « Elles se sont ___ la main. »', ['serré', 'serrées', 'serrés', 'serrer'],
                    'Le complément « la main » est placé après le verbe : le participe passé ne s\'accorde pas. Elles se sont serré la main.', 'Regarde ce qui vient après le verbe.'],
                ['Quel mot est bien écrit ?', ['Bonhomme', 'Bonnhomme', 'Bonhome', 'Bonomme'],
                    'On écrit « bonhomme », avec un seul n et deux m. Au pluriel : des bonshommes.', 'Un seul n.'],
                ['Quel est le féminin de « acteur » ?', ['Actrice', 'Acteuse', 'Acteure', 'Actreuse'],
                    'Beaucoup de noms en -teur font leur féminin en -trice : acteur, actrice ; directeur, directrice.', 'Comme « directeur ».'],
                ['Dans « Le chat dort sur le canapé », quel est le sujet ?', ['Le chat', 'dort', 'sur le canapé', 'le canapé'],
                    'Le sujet fait l\'action du verbe. Qui dort ? Le chat.', 'Demande-toi : qui dort ?'],
                ['Complète : « Il faut que tu ___ à l\'heure. »', ['sois', 'es', 'soit', 'est'],
                    '« Il faut que » appelle le subjonctif. Avec « tu » : que tu sois. « Soit » s\'emploie avec il ou elle.', 'C\'est le subjonctif, avec « tu ».'],
                ['Lequel de ces mots est un adverbe ?', ['Rapidement', 'Rapide', 'Rapidité', 'Rapides'],
                    'L\'adverbe modifie un verbe ou un adjectif : il court rapidement. Beaucoup d\'adverbes se terminent en -ment.', 'Il se termine souvent en -ment.'],
                ['Quelle est la bonne orthographe ?', ['Malgré', 'Malgrés', 'Malgret', 'Malgrè'],
                    '« Malgré » est une préposition : elle ne prend jamais de s, et s\'écrit avec un accent aigu.', 'Un accent aigu, rien après.'],
            ],
        ],
        [
            'titre' => 'Le sens des mots',
            'slug' => 'le-sens-des-mots',
            'description' => 'Synonymes, contraires et expressions imagées.',
            'questions' => [
                ['Quel mot est un synonyme de « rapide » ?', ['Véloce', 'Lent', 'Lourd', 'Paisible'],
                    '« Véloce » veut dire rapide, agile. Il a donné le mot « vélo ».', 'Il a donné le mot « vélo ».'],
                ['Quel est le contraire de « généreux » ?', ['Avare', 'Prodigue', 'Aimable', 'Riche'],
                    'L\'avare garde tout pour lui. « Prodigue », au contraire, désigne quelqu\'un qui dépense sans compter.', 'Pense à la pièce de Molière.'],
                ['Que signifie « avoir le cafard » ?', ['Être triste', 'Avoir peur', 'Être en colère', 'Avoir faim'],
                    'Avoir le cafard, c\'est avoir des idées noires, comme l\'insecte.', 'L\'insecte est noir.'],
                ['Que veut dire « poser un lapin » ?', ['Ne pas venir à un rendez-vous', 'Faire une blague', 'Partir en courant', 'Offrir un cadeau'],
                    'Poser un lapin à quelqu\'un, c\'est le laisser attendre à un rendez-vous où l\'on ne vient pas.', 'Quelqu\'un attend pour rien.'],
                ['Qu\'est-ce qu\'un homonyme ?', ['Un mot qui se prononce comme un autre mais n\'a pas le même sens', 'Un mot qui a le même sens qu\'un autre', 'Un mot de sens contraire', 'Un mot venu d\'une autre langue'],
                    'Les homonymes se prononcent pareil mais ne veulent pas dire la même chose : verre, vert, ver, vers.', 'Pense à « vert » et « verre ».'],
                ['Que veut dire « s\'évertuer à » ?', ['Faire de grands efforts pour', 'Renoncer à', 'Se moquer de', 'Oublier de'],
                    'S\'évertuer à faire quelque chose, c\'est s\'y appliquer avec beaucoup d\'efforts.', 'C\'est le contraire d\'abandonner.'],
                ['De quelle langue vient le mot « algèbre » ?', ['De l\'arabe', 'Du latin', 'Du grec', 'De l\'anglais'],
                    '« Algèbre » vient de l\'arabe « al-jabr », tiré du titre d\'un traité du mathématicien al-Khwârizmî, au IXe siècle.', 'Comme « zéro » et « chiffre ».'],
                ['Qu\'est-ce qu\'un bibliophile ?', ['Une personne qui aime les livres', 'Un vendeur de bibles', 'Un collectionneur de timbres', 'Un employé de bibliothèque'],
                    '« Biblio » veut dire livre et « phile », qui aime. Le collectionneur de timbres est un philatéliste.', '« -phile » veut dire « qui aime ».'],
            ],
        ],
    ],
];
