<?php

return [
    'nom' => 'Culture générale',
    'slug' => 'culture-generale',
    'description' => 'Un peu de tout, et les grandes découvertes.',
    'onglet' => 'lilas',
    'quiz' => [
        [
            'titre' => 'Un peu de tout',
            'slug' => 'un-peu-de-tout',
            'description' => 'Des questions de tous les jours, pour s\'échauffer.',
            'questions' => [
                ['Combien de côtés a un hexagone ?', ['6', '5', '7', '8'],
                    '« Hexa » veut dire six en grec. Le pentagone en a cinq, l\'octogone huit.', 'Comme les alvéoles d\'une ruche.'],
                ['Quel animal fabrique le miel ?', ['L\'abeille', 'La guêpe', 'La fourmi', 'Le papillon'],
                    'L\'abeille butine le nectar des fleurs et le transforme en miel dans la ruche.', 'Elle vit en ruche.'],
                ['Qui a peint La Joconde ?', ['Léonard de Vinci', 'Michel-Ange', 'Pablo Picasso', 'Vincent van Gogh'],
                    'Léonard de Vinci a peint La Joconde au début du XVIe siècle. Elle est exposée au musée du Louvre, à Paris.', 'Un peintre et inventeur italien.'],
                ['Combien de joueurs une équipe de football aligne-t-elle sur le terrain ?', ['11', '9', '10', '12'],
                    'Une équipe de football joue à onze : dix joueurs de champ et un gardien.', 'Gardien compris.'],
                ['À quelle température l\'eau bout-elle au niveau de la mer ?', ['100 °C', '90 °C', '120 °C', '80 °C'],
                    'Au niveau de la mer, l\'eau bout à 100 °C. En haute montagne, elle bout plus tôt, car la pression de l\'air est plus faible.', 'Un nombre rond.'],
                ['Quel instrument a des touches noires et blanches ?', ['Le piano', 'Le violon', 'La flûte', 'La batterie'],
                    'Un piano classique compte 88 touches : 52 blanches et 36 noires.', 'Il a souvent 88 touches.'],
                ['Combien de minutes y a-t-il dans une heure et demie ?', ['90', '60', '120', '150'],
                    'Une heure fait 60 minutes, une demi-heure 30 : 60 + 30 = 90 minutes.', '60 + 30.'],
                ['Quel est l\'animal terrestre le plus rapide ?', ['Le guépard', 'Le lion', 'Le cheval', 'L\'antilope'],
                    'Le guépard dépasse les 100 km/h en pointe, mais seulement sur de courtes distances.', 'Un félin tacheté.'],
            ],
        ],
        [
            'titre' => 'Inventions et découvertes',
            'slug' => 'inventions-et-decouvertes',
            'description' => 'Les savants et les idées qui ont changé notre vie.',
            'questions' => [
                ['Qui a découvert la pénicilline en 1928 ?', ['Alexander Fleming', 'Louis Pasteur', 'Marie Curie', 'Isaac Newton'],
                    'Alexander Fleming remarque qu\'une moisissure tue les bactéries de ses cultures. La pénicilline devient le premier antibiotique.', 'Un médecin écossais.'],
                ['Quelle scientifique a reçu deux prix Nobel, en physique puis en chimie ?', ['Marie Curie', 'Rosalind Franklin', 'Ada Lovelace', 'Lise Meitner'],
                    'Marie Curie reçoit le Nobel de physique en 1903 et celui de chimie en 1911, pour ses travaux sur la radioactivité.', 'Elle a étudié la radioactivité.'],
                ['Qui est l\'auteur de la théorie de la relativité ?', ['Albert Einstein', 'Galilée', 'Isaac Newton', 'Charles Darwin'],
                    'Albert Einstein publie la relativité restreinte en 1905 puis la relativité générale en 1915.', 'Sa formule la plus célèbre est E = mc².'],
                ['Quel appareil Alexander Graham Bell a-t-il fait breveter en 1876 ?', ['Le téléphone', 'La radio', 'La télévision', 'L\'ampoule électrique'],
                    'Bell dépose le brevet du téléphone en 1876. L\'ampoule est associée à Edison, la radio à Marconi.', 'On l\'utilise pour parler à distance.'],
                ['Qui a mis au point le vaccin contre la rage en 1885 ?', ['Louis Pasteur', 'Robert Koch', 'Edward Jenner', 'Alexander Fleming'],
                    'Louis Pasteur vaccine contre la rage le jeune Joseph Meister en 1885. Edward Jenner avait inventé le vaccin contre la variole un siècle plus tôt.', 'Un savant français.'],
                ['Qu\'a découvert Galilée avec sa lunette en 1610 ?', ['Des satellites de Jupiter', 'Les anneaux d\'Uranus', 'La planète Neptune', 'Une galaxie lointaine'],
                    'Galilée observe quatre lunes autour de Jupiter : la preuve que tout ne tourne pas autour de la Terre.', 'Quatre petits points autour d\'une planète.'],
                ['Quel langage fait réagir les pages web dans le navigateur depuis 1995 ?', ['JavaScript', 'Python', 'Fortran', 'Cobol'],
                    'JavaScript a été créé en 1995 pour le navigateur Netscape. Il tourne aujourd\'hui dans tous les navigateurs, y compris pour ce quiz.', 'Il fait tourner ce quiz.'],
                ['Qui a formulé la théorie de l\'évolution par la sélection naturelle ?', ['Charles Darwin', 'Gregor Mendel', 'Jean-Baptiste Lamarck', 'Carl von Linné'],
                    'Charles Darwin publie « L\'Origine des espèces » en 1859. Mendel, lui, a découvert les lois de l\'hérédité.', 'Il a voyagé aux îles Galápagos.'],
            ],
        ],
    ],
];
